name: flutter_social
description: A new Flutter application.
version: 2.0.0+2
publish_to: 'none'
environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  async: 2.8.2
  auto_size_text: 3.0.0
  awesome_dialog: 2.1.2
  algolia: ^1.1.1
  badges: 2.0.2
  bot_toast: 4.0.1
  cached_network_image: 3.2.0
  cloud_firestore: 3.1.8
  cloud_functions: 3.2.7
  collection: 1.15.0
  connectivity_plus: 2.2.1
  countries: 0.0.5+2
  cupertino_icons: 1.0.4
  change_app_package_name: ^1.0.0
  day_night_switcher: 0.2.0+1
  deep_pick: 0.10.0
  equatable: 2.0.3
  firebase_analytics: 9.1.0
  firebase_auth: 3.3.7
  firebase_core: 1.12.0
  firebase_crashlytics: 2.5.1
  firebase_messaging: 11.2.6
  firebase_storage: 10.2.7
  flare_flutter: 3.0.2
  flutter_blurhash: 0.6.4
  flutter_cache_manager: 3.3.0
  flutter_image_compress: 1.1.0
  flutter_linkify: 5.0.2
  flutter_settings_ui: ^2.0.1
  flutter_spinkit: 5.1.0
  flutter_staggered_grid_view: 0.6.1
  flutterfire_ui: 0.3.4
  focused_menu: 1.0.5
  font_awesome_flutter: 9.2.0
  freezed_annotation: 1.1.0
  get: 4.6.1
  google_fonts: 2.3.1
  google_mobile_ads: 1.1.0
  image_crop: 0.4.0
  image_downloader: 0.31.0
  image_picker: 0.8.4+9
  infinite_scroll_pagination: 3.1.0
  intl: 0.17.0
  logger: 1.1.0
  modal_bottom_sheet: 2.0.0
  paginated_search_bar: ^1.1.2
  path: 1.8.0
  path_provider: 2.0.9
  permission_handler: 9.1.0
  photo_view: 0.13.0
  pin_code_fields: 7.3.0
  profanity_filter: 2.0.0
  pull_to_refresh: 2.0.0
  share_plus: 3.1.0
  shared_preferences: 2.0.13
  shimmer: 2.0.0
  timeago: 3.2.2
  universal_html: 2.0.8
  url_launcher: 6.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.1.7
  fast_i18n: 5.11.0
  flutter_launcher_icons: 0.9.2
  freezed: 1.1.1
  lint: 1.8.2

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/flare/

flutter_icons:
  image_path: 'assets/app_icon.png'
  android: true
  ios: true

flutter_native_splash:
  color: '#ffffff'
  color_dark: '#000000'
  image: assets/app_icon.png
  image_dark: assets/app_icon.png
  android: true
  ios: true
  web: true
  fullscreen: true

scripts:
  gen: flutter pub run build_runner build
  genr: flutter pub run build_runner build --delete-conflicting-outputs
  web_skia: flutter run -d chrome --dart-define=FLUTTER_WEB_USE_SKIA=true
  build_web_skia: flutter build web --dart-define=FLUTTER_WEB_USE_SKIA=true
  loc: flutter pub run fast_i18n
  icons: flutter pub run flutter_launcher_icons:main
  splash: flutter pub run flutter_native_splash:create
  splash_remove: flutter pub run flutter_native_splash:remove
  clean:
    - flutter clean
    - flutter pub get
    - dart fix --apply
    - flutter format .
    - flutter analyze .
# keytool -list -v -alias androiddebugkey -keystore ~/.android/debug.keystore
# keytool -list -v -alias key0 -keystore android/app/keystore
